---
# tasks file for ansible-postgresql
- name: PostgreSQL server package is installed
  yum:
    name: ['postgresql-server', 'postgresql-contrib']
    state: "present"
  notify:
    - restart postgresql
