---
# tasks file for ansible-postgresql
- name: PostgreSQL server package is installed
  yum:
    name: {{ item }}
    state: "present"
  with_items:
    - postgresql-server
    - postgresql-contrib
  notify:
    - restart postgresql
